config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	root 'pages#phonebook'
	
	resources :contacts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
	validates :name, :number, :desription, presence: true
end

app/models/page.rb
class Page < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

	def new
		@contact = Contact.new
	end
	
	def create
		@contact = Contact.new(contact_params)
		
		if @contact.save
			redirect_to contacts_path
		else
			render :new
		end
	end
	
	def index
		@contacts = Contact.all
	end
	
	def edit
		@contact = Contact.find(params[:id])
	end
	
	def update
		@contact = Contact.find(params[:id])
		if @contact.update(contact_params)
			redirect_to contacts_path
		else
			render :edit
		end
	end
	
	def show
		@contact = Contact.find(params[:id])		
	end
	
	def destroy
		@contact = Contact.find(params[:id])
		if @contact.destroy
			redirect_to contacts_path
		else
			redirect_to contacts_path, error: 'Failure'
		end
	end
	
	private	
		def contact_params
			params[:contact].permit(:name, :number, :desription)
		end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def phonebook
		redirect_to contacts_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
	<%= f.input :name %>
	<%= f.input :number %>
	<%= f.input :desription %>
	
	<%= f.button :submit %>
<% end %>

app/views/contacts/edit.html.erb
<h1>Edit contact</h1>

<%= render 'form' %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<table class='table'>
	<thead>
		<tr>
			<th>Name</th>
			<th>Number</th>
		</tr>
	</thead>
	
	<tbody>
		<% @contacts.each do |contact| %>
			<tr>
				<td>
					<%= contact.name %>
				</td>
				<td>
					<%= contact.number %>
				</td>
				<td>
					<%= link_to 'Details', contact_path(contact), method: :get %>
				</td>
				<td>
					<%= link_to 'Edit', edit_contact_path(contact) %>
				</td>
				<td>
					<%= link_to 'Delete', contact_path(contact), method: :delete, data: {confirm: 'Are you sure?'} %>
				</td>
			</tr>
		<% end %>
	</tbody>
</table>
<p><%= link_to 'Add new contact', new_contact_path() %></p>

app/views/contacts/new.html.erb
<h1>New contact</h1>

<%= simple_form_for(@contact) do |f| %>
	<%= f.input :name %>
	<%= f.input :number %>
	<%= f.input :desription %>
	
	<%= f.button :submit %>
<% end %>

app/views/contacts/show.html.erb
<h1><%= @contact.name %></h1>

<h3><%= @contact.number %><h3>

<p><%= @contact.desription %><p>

<p><%= link_to 'Edit', edit_contact_path(@contact) %>
<%= link_to 'Delete', contact_path(@contact), method: :delete, data: {confirm: 'Are you sure?'} %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PhoneBook" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/new.html.erb
<h1>New contact</h1>

<%= render 'form' %>

app/views/pages/phonebook.html.erb
<h4>
	<%= @title %>
<h4>
<p>
	<%= @text %>
</p>